### ISSUE TITLE
1.1.1 version todo

### ISSUE THREAD

**Issue by pdh0927** [pdh0927/keyket#101]
- [x] fix fixed bucket list error 
- [x] add pin border
- [x] fix release first load error
